apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-output-gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/HaiNguyen-python/KubernetesSubmissions.git
    targetRevision: HEAD
    path: the_project/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
