apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-project-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-project
  template:
    metadata:
      labels:
        app: main-project
    spec:
      containers:
      - name: main-project
        image: gcr.io/project-5537670b-93d7-476f-9b4/main-project:v1.0
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 10
