apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc # Tên Service phải là ping-pong-svc
  namespace: exercises
spec:
  type: NodePort
  selector:
    app: ping-pong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
