apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-logs    # Volume nội bộ (giữa Reader & Writer)
          emptyDir: {}
        - name: ping-pong-data # Volume chung với Ping-pong (PVC)
          persistentVolumeClaim:
            claimName: ping-pong-pvc
      containers:
        # Container Writer (Giữ nguyên)
        - name: log-output-writer
          image: hainguyen95/log-output:v3 
          command: ["python", "-u", "writer.py"]
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files

        # Container Reader (Cập nhật image v4 và mount thêm PVC)
        - name: log-output-reader
          image: hainguyen95/log-output:v4
          command: ["python", "-u", "reader.py"]
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
            - name: ping-pong-data
              mountPath: /usr/src/app/data
